# Generated by Django 5.0.6 on 2024-06-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='history',
        ),
    ]
