# Generated by Django 5.0.6 on 2024-06-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_analysishistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='AnalysisHistory',
        ),
    ]
