# Generated by Django 5.0.6 on 2024-06-20 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_user_chat_history_chathistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
