# Generated by Django 5.0.6 on 2024-06-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_image_chathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.image'),
        ),
    ]
